# .goreleaser.yaml
version: 2

project_name: ai-chat-md-export

before:
  hooks:
    - bun install --frozen-lockfile

builds:
  - id: ai-chat-md-export
    builder: bun
    binary: ai-chat-md-export
    main: ./src/cli.ts
    targets:
      - darwin-x64      # macOS Intel
      - darwin-arm64    # macOS Apple Silicon
      - linux-x64       # Linux x64
      - linux-arm64     # Linux ARM64
      - windows-x64     # Windows x64

archives:
  - id: default
    builds:
      - ai-chat-md-export
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

release:
  # Use existing release created by release-please
  mode: keep-existing
  
  # Don't create new release or update notes
  disable: false

checksum:
  name_template: "SHA256SUMS.txt"
  algorithm: sha256

changelog:
  # Disable changelog generation since release-please handles it
  disable: true

brews:
  - name: ai-chat-md-export
    # GitHub repository to push the formula to
    repository:
      owner: sugurutakahashi-1234
      name: homebrew-tap
      branch: main
      # Use GitHub App token or PAT with repo permissions
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
      
    # Git author for formula commits
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com
      
    # Commit message template
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    
    # Formula folder inside the tap repository
    directory: Formula
    
    # Homepage for the formula
    homepage: "https://github.com/sugurutakahashi-1234/{{ .ProjectName }}"
    
    # Formula description
    description: "CLI tool to convert ChatGPT and Claude chat history to Markdown"
    
    # License
    license: "MIT"
    
    # No dependencies needed - Bun compiles to standalone binary
    
    # Installation steps
    install: |
      bin.install "ai-chat-md-export"
    
    # Test block
    test: |
      assert_match "ai-chat-md-export", shell_output("#{bin}/ai-chat-md-export --help")

# Announce release in various channels
announce:
  skip: true  # Can enable later for Discord, Slack, Twitter, etc.
