# .goreleaser.yaml
# GoReleaser configuration reference: https://goreleaser.com/customization/
version: 2

project_name: ai-chat-md-export

before:
  hooks:
    - bun install --frozen-lockfile

# Bun Builder configuration
# https://goreleaser.com/customization/builds/bun/
builds:
  - id: ai-chat-md-export
    builder: bun
    binary: ai-chat-md-export
    main: ./src/presentation/cli.ts
    targets:
      - darwin-x64          # macOS Intel
      - darwin-arm64        # macOS Apple Silicon
      - linux-x64-modern    # Linux x64 (modern CPUs with AVX2)
      - linux-arm64         # Linux ARM64 (Raspberry Pi, AWS Graviton, etc.)
      - windows-x64-modern  # Windows x64 (modern CPUs with AVX2)

# Archive configuration
# https://goreleaser.com/customization/archive/
# Migration guide: https://goreleaser.com/deprecations#archivesformat
archives:
  - id: default
    ids:
      - ai-chat-md-export
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

# Release configuration
# https://goreleaser.com/customization/release/
release:
  # Use existing release created by release-please
  mode: keep-existing
  
  # Don't create new release or update notes
  disable: false

checksum:
  name_template: "SHA256SUMS.txt"
  algorithm: sha256

changelog:
  # Disable changelog generation since release-please handles it
  disable: true

# Homebrew Casks configuration (replacement for deprecated 'brews')
# https://goreleaser.com/customization/homebrew_casks/
# Migration from brews: https://goreleaser.com/deprecations#brews
homebrew_casks:
  - name: ai-chat-md-export
    # GitHub repository to push the formula to
    repository:
      owner: sugurutakahashi-1234
      name: homebrew-tap
      branch: main
      # Use GitHub App token or PAT with repo permissions
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
      
    # Git author for formula commits
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@users.noreply.github.com
      
    # Commit message template
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    
    # Formula folder inside the tap repository
    directory: Casks
    
    # Conflicts with existing formula (if any)
    conflicts:
      - formula: ai-chat-md-export
    
    # Homepage for the formula
    homepage: "https://github.com/sugurutakahashi-1234/{{ .ProjectName }}"
    
    # Formula description
    description: "CLI tool to convert ChatGPT and Claude chat history to Markdown"
    
    # License
    license: "MIT"
    
    # No dependencies needed - Bun compiles to standalone binary
    
    # Post-install hook to remove quarantine attributes
    # This prevents macOS Gatekeeper from blocking the binary
    # Reference: https://goreleaser.com/customization/homebrew_casks/#signing-and-notarizing
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-chat-md-export"]
          end

# Announce release in various channels
announce:
  skip: true  # Can enable later for Discord, Slack, Twitter, etc.
