[test]
# This configuration is intentionally minimal because the primary goal is to write meaningful tests,
# not just to achieve high coverage numbers. Therefore, only the minimum required coverage is enforced.
# Ref: https://bun.com/docs/test/coverage
coverageThreshold = { lines = 0.50, functions = 0.50 }
coverageSkipTestFiles = true
coverageDir = "coverage"
coverageReporter = ["text", "lcov"]
