// This file is auto-updated by release tools:
// - release-please: Automatically updates on PR merge (primary method)
// - release-it: Updates directly via @release-it/bumper plugin
// DO NOT EDIT THIS FILE MANUALLY
//
// IMPORTANT: If moving this file to a different directory, update the following configuration files:
// - release-please-config.json: extra-files[0].path
// - .release-it.json: plugins["@release-it/bumper"].out.file
// x-release-please-start-version
export const VERSION = "0.7.6";
// x-release-please-end
