// This file is auto-updated by release tools:
// - release-please: Automatically updates on PR merge (primary method)
// - release-it: Updates directly via @release-it/bumper plugin
// DO NOT EDIT THIS FILE MANUALLY
// x-release-please-start-version
export const VERSION = "0.5.0";
// x-release-please-end
