name: branch-lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install only git-branch-lint
        run: bun add -D @elsikora/git-branch-lint

      - name: Validate branch name
        run: bunx @elsikora/git-branch-lint