name: Branch Name Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  create:
    branches:
      - '**'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Validate branch name
        run: bun run git-branch-lint