name: branch-lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  validate-branch-name:
    # Skip draft PRs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Validate branch name
        run: bunx @elsikora/git-branch-lint