name: ci-pull-request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  ci-pull-request:
    # Skip draft PRs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint:check

      - name: Build
        run: bun run build

      - name: Check dependencies
        run: bun run knip

      - name: Test
        run: bun run test:coverage

      - name: Generate TypeScript dependency graph
        uses: ysk8hori/delta-typescript-graph-action@v1.2.3
        with:
          tsconfig: './tsconfig.dependency-graph.json' # Use dedicated config instead of tsconfig.json to include test files in dependency analysis
          orientation: 'LR' # Change to 'TB' for top-bottom orientation
          max-size: 30 # default is 30, adjust as needed
          show-metrics: true
          comment-title: '📊 Dependency Graph Changes'
          in-details: true
          include-index-file-dependencies: false # Set to true if you want to include index.ts dependencies
          debug: true

      - name: Upload coverage to Codecov
        if: github.actor != 'github-actions[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}     # Required for private repos
          files: ./coverage/lcov.info             # Path to coverage report
          verbose: true                           # Enable verbose logging for debugging
          fail_ci_if_error: false                 # Don't fail CI if upload fails
          flags: unittests                        # Tag coverage as unit tests
          disable_search: false                   # Enable automatic coverage file search
          report_type: coverage                   # Specify coverage report type

      - name: Install LCOV
        if: github.event_name == 'pull_request'
        run: |
          # Skip update if not needed (saves ~10s)
          sudo apt-get install -y lcov || (sudo apt-get update && sudo apt-get install -y lcov)

      - name: Report code coverage
        if: github.event_name == 'pull_request' && github.actor != 'github-actions[bot]'
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: ./coverage/lcov.info
          artifact-name: code-coverage-report
          minimum-coverage: 75
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title-prefix: '📊 '
          additional-message: 'Code coverage report for this PR'
          update-comment: true
