name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22, 24]  # Latest LTS + current

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint:check

      - name: Build
        run: bun run build

      - name: Test
        run: bun test

      - name: Test coverage
        run: bun test --coverage

      - name: Check dependencies
        run: bun run knip

  test-binary:
    runs-on: ubuntu-latest  # Cost-effective: macOS is 10x more expensive
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: bun run build

      - name: Test binary
        run: bun test tests/binary
        
      - name: Test CLI help
        run: ./dist/ai-chat-md-export --help