name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          echo "=== System info ==="
          uname -a
          echo "=== Bun version ==="
          bun --version
          echo "=== Installing dependencies ==="
          # Use npm to install @biomejs/biome to ensure platform-specific binary is installed
          npm install --no-save @biomejs/cli-linux-x64
          bun install --frozen-lockfile
          echo "=== Checking node_modules/@biomejs ==="
          ls -la node_modules/@biomejs/ || echo "Directory not found"
          echo "=== Checking biome binary ==="
          which biome || echo "biome not in PATH"
          echo "=== Try running biome with bunx ==="
          bunx @biomejs/biome --version || echo "bunx biome failed"

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: |
          echo "=== Before lint check ==="
          ls -la node_modules/@biomejs/
          echo "=== Running lint:check ==="
          bun run lint:check || (echo "=== Lint failed, trying with bunx ===" && bunx @biomejs/biome check .)

      - name: Build
        run: bun run build

      - name: Check dependencies
        run: bun run knip

      - name: Test
        run: bun run test:coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false

      - name: Report code coverage
        if: github.event_name == 'pull_request'
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: ./coverage/lcov.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          title-prefix: '📊 '
