name: force-version-bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version WITHOUT v prefix (e.g., 0.7.0)'
        required: true
        type: string
      reason:
        description: 'Reason for version bump'
        required: false
        default: 'Force version bump to resolve version mismatch'
        type: string

permissions:
  contents: write

jobs:
  create-release-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit with Release-As
        env:
          HUSKY: 0
        run: |
          git commit --allow-empty -m "chore: ${{ github.event.inputs.reason }}

          Release-As: ${{ github.event.inputs.version }}"

      - name: Push to main
        run: git push origin main