name: pr-auto-assign

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  pr-auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/pr-auto-assign-config.yml'
