name: Windows Test

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Note
        run: |
          echo "Windows testing requires Bun for TypeScript execution."
          echo "Since Bun doesn't support Windows natively, we skip detailed tests."
          echo "The npm package will still work on Windows when installed globally."
