name: validate-pr-title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: write  # Required to read PR information
  statuses: write       # Required for WIP status updates

jobs:
  check-title:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Subject must start with lowercase and be max 72 chars
          subjectPattern: ^(?![A-Z]).{1,72}$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            must start with a lowercase letter and be 72 characters or less.

            ✅ Good: "feat: add new feature" (lowercase, under 72 chars)
            ❌ Bad: "feat: Add new feature" (uppercase)
            ❌ Bad: "feat: this is a very long commit message that exceeds the maximum allowed length of 72 characters" (too long)

          # Allow WIP PRs
          wip: true
