name: validate-branch-name

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  validate-branch-name:
    # Skip draft PRs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Validate branch name
        run: |
          # GitHub Actions checks out in detached HEAD state
          # Use the PR head branch name from the event context
          export GIT_BRANCH_LINT_BRANCH_NAME="${{ github.head_ref }}"
          bun run validate:branch